version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    groups:
      production-minor-and-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-minor-and-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gomod"
    directory: "/oracle-backend"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore(deps/go)"
    labels:
      - "dependencies"
      - "backend"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore(ci)"
    labels:
      - "dependencies"
      - "ci"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/oracle-backend"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore(deps/docker)"
    labels:
      - "dependencies"
      - "backend"
    open-pull-requests-limit: 5
