// filepath: extension/tests/locales-generated.test.ts
/**
 * Drift guards for the generated chrome.i18n `_locales` tree.
 *
 * The single source of truth is TRANSLATIONS in entrypoints/content/i18n.ts;
 * `extension/_locales/<locale>/messages.json` is generated by
 * tools/generate-locales.mjs. These tests pin both directions of that
 * contract, so a translation edit without regeneration fails the unit suite
 * (CI additionally runs the generator + `git diff --exit-code`).
 */
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { TRANSLATIONS } from '../entrypoints/content/i18n';
import { t } from '../entrypoints/content/i18n';
import type { LangKey } from '../entrypoints/content/i18n';
import {
  buildAllLocales,
  buildLocaleMessages,
  diffAgainstDisk,
  fromDirName,
  loadTranslationsFromSource,
  manifestDeclaresDefaultLocale,
  toDirName,
  toMessageKey,
} from '../tools/generate-locales.mjs';

const EXTENSION_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const LOCALES_DIR = path.join(EXTENSION_ROOT, '_locales');

describe('generate-locales key/locale mapping', () => {
  it('maps camelCase t() keys to chrome.i18n message names deterministically', () => {
    expect(toMessageKey('download')).toBe('download');
    expect(toMessageKey('ariaDownload')).toBe('aria_download');
    expect(toMessageKey('titleQuick')).toBe('title_quick');
    expect(toMessageKey('downloadAll')).toBe('download_all');
    expect(toMessageKey('after_posting')).toBe('after_posting');
  });

  it('rejects keys that would produce invalid chrome.i18n message names', () => {
    expect(() => toMessageKey('has space')).toThrow(/not a valid chrome\.i18n message name/);
    expect(() => toMessageKey('')).toThrow();
  });

  it('maps locale codes to chrome.i18n underscore directory names', () => {
    expect(toDirName('en')).toBe('en');
    expect(toDirName('pt-pt')).toBe('pt_PT');
    expect(toDirName('zh-cn')).toBe('zh_CN');
    expect(toDirName('zh-tw')).toBe('zh_TW');
    expect(toDirName('sr-latn')).toBe('sr_Latn');
    expect(toDirName('xx-pirate')).toBe('xx_pirate'); // BCP47: variants lowercase; chrome matches dirs case-insensitively
  });

  it('maps chrome.i18n directory names back to TRANSLATIONS locale codes', () => {
    for (const locale of Object.keys(TRANSLATIONS)) {
      expect(fromDirName(toDirName(locale))).toBe(locale);
    }
  });
});

describe('generate-locales buildLocaleMessages (fixture round-trip)', () => {
  it('round-trips a fixture subset with exact message bytes and original keys', () => {
    const fixture = {
      en: { download: 'Download', ariaDownload: 'Download', after_posting: 'after posting' },
      'zh-cn': { download: '下载', after_posting: '发布后' },
    };
    const files = buildAllLocales(fixture);
    expect(Object.keys(files).sort()).toEqual(['en', 'zh_CN']);
    expect(files.en).toBe(
      [
        '{',
        '  "download": {',
        '    "message": "Download",',
        '    "description": "download"',
        '  },',
        '  "aria_download": {',
        '    "message": "Download",',
        '    "description": "ariaDownload"',
        '  },',
        '  "after_posting": {',
        '    "message": "after posting",',
        '    "description": "after_posting"',
        '  }',
        '}',
        '',
      ].join('\n'),
    );
    const parsed = JSON.parse(files.zh_CN);
    expect(parsed.download).toEqual({ message: '下载', description: 'download' });
    expect(parsed.after_posting.message).toBe('发布后');
  });

  it('skips locales without any non-empty translation', () => {
    const files = buildAllLocales({ en: { download: 'Download' }, empty: { download: '' } });
    expect(Object.keys(files)).toEqual(['en']);
  });

  it('fails loudly when a translation contains "$" (chrome.i18n placeholder territory)', () => {
    expect(() => buildLocaleMessages('en', { price: 'costs $5' })).toThrow(/contains "\$"/);
  });

  it('fails on case-colliding message names (chrome.i18n names are case-insensitive)', () => {
    expect(() => buildLocaleMessages('en', { downloadAll: 'a', download_all: 'b' })).toThrow(/collides/);
  });

  it('fails on non-string translation values', () => {
    expect(() => buildLocaleMessages('en', { download: 42 as unknown as string })).toThrow(/expected string/);
  });
});

describe('_locales tree consistency with TRANSLATIONS', () => {
  it('has a messages.json for every locale in TRANSLATIONS and nothing else', () => {
    expect(existsSync(LOCALES_DIR)).toBe(true);
    const onDisk = readdirSync(LOCALES_DIR).filter((name) => statSync(path.join(LOCALES_DIR, name)).isDirectory());
    const expected = Object.keys(TRANSLATIONS).map(toDirName);
    expect(onDisk.sort()).toEqual(expected.slice().sort());
  });

  it('matches a fresh regeneration byte-for-byte (drift guard both directions)', () => {
    const generated = buildAllLocales(TRANSLATIONS);
    expect(diffAgainstDisk(generated)).toEqual([]);
  });

  it('en table: every t() key exists in _locales/en with byte-identical text', () => {
    const enFile = JSON.parse(readFileSync(path.join(LOCALES_DIR, 'en', 'messages.json'), 'utf8'));
    for (const [key, value] of Object.entries(TRANSLATIONS.en)) {
      const entry = enFile[toMessageKey(key)];
      expect(entry, `missing _locales/en message for t() key "${key}"`).toBeDefined();
      expect(entry.message).toBe(value);
      expect(entry.description).toBe(key);
    }
  });

  it('en file: every message maps back to a real t() key via description', () => {
    const enFile = JSON.parse(readFileSync(path.join(LOCALES_DIR, 'en', 'messages.json'), 'utf8'));
    for (const [messageKey, entry] of Object.entries(enFile as Record<string, { message: string; description: string }>)) {
      expect(messageKey).toMatch(/^[a-zA-Z0-9_]+$/);
      expect(TRANSLATIONS.en[entry.description as LangKey]).toBe(entry.message);
    }
  });

  it('every locale entry keeps the exact TRANSLATIONS string and original key as description', () => {
    for (const [locale, table] of Object.entries(TRANSLATIONS)) {
      const file = JSON.parse(readFileSync(path.join(LOCALES_DIR, toDirName(locale), 'messages.json'), 'utf8')) as Record<string, { message: string; description: string }>;
      expect(Object.keys(file).length).toBe(Object.keys(table).length);
      for (const [key, value] of Object.entries(table)) {
        const entry = file[toMessageKey(key)];
        expect(entry?.message, `${locale}/${key}`).toBe(value);
        expect(entry?.description, `${locale}/${key}`).toBe(key);
      }
    }
  });
});

describe('generator source loader (typescript transpile path)', () => {
  it('loads TRANSLATIONS from i18n.ts matching the module graph import', async () => {
    const loaded = await loadTranslationsFromSource();
    expect(Object.keys(loaded).length).toBe(Object.keys(TRANSLATIONS).length);
    expect(JSON.stringify(loaded)).toBe(JSON.stringify(TRANSLATIONS));
  });
});

describe('t() behavior unchanged (TRANSLATIONS remains the runtime source)', () => {
  beforeEach(() => {
    vi.resetModules();
    document.documentElement.lang = '';
  });

  it('resolves every en key to the exact TRANSLATIONS string', async () => {
    const mod = await import('../entrypoints/content/i18n');
    for (const [key, value] of Object.entries(TRANSLATIONS.en)) {
      expect(mod.t(key as LangKey)).toBe(value);
    }
  });

  it('falls back to en when the detected language lacks a key (unchanged)', async () => {
    document.documentElement.lang = 'sr-Latn'; // sr-latn table lacks cancel/cancelled/cancelAll
    const mod = await import('../entrypoints/content/i18n');
    expect(mod.getCurrentCachedLanguage()).toBe('sr-latn');
    expect(mod.t('cancel')).toBe(TRANSLATIONS.en.cancel);
  });
});

describe('bundle copy gate (bead 770: chrome requires default_locale with _locales)', () => {
  it('detects default_locale declarations in wxt config files', () => {
    expect(manifestDeclaresDefaultLocale('/nonexistent/wxt.config.ts')).toBe(false);
  });

  it('bundle copy is active now that the manifest declares default_locale', () => {
    // Bead 770 landed (2026-09-18): wxt.config.ts declares
    // default_locale: 'en' and the generator ships _locales into the bundle
    // root (src/, the publicDir). The coupling stays enforced from both
    // directions: the detector below must agree with the real manifest, and
    // the bundle copy must exist so Chrome never sees one without the other.
    expect(manifestDeclaresDefaultLocale()).toBe(true);
    expect(existsSync(path.join(EXTENSION_ROOT, 'src', '_locales'))).toBe(true);
    expect(
      existsSync(path.join(EXTENSION_ROOT, 'src', '_locales', 'en', 'messages.json')),
    ).toBe(true);
  });
});
